import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#ffffff",
        "surface-dim": "#f3f4f6",
        "surface-bright": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f9fafb",
        "surface-container": "#f3f4f6",
        "surface-container-high": "#e5e7eb",
        "surface-container-highest": "#d1d5db",
        "on-surface": "#111827",
        "on-surface-variant": "#4b5563",
        "inverse-surface": "#1f2937",
        "inverse-on-surface": "#f9fafb",
        outline: "#9ca3af",
        "outline-variant": "#e5e7eb",
        "surface-tint": "#ff6b2b",
        primary: "#ff6b2b",
        "on-primary": "#ffffff",
        "primary-container": "#ffebd8",
        "on-primary-container": "#331200",
        "inverse-primary": "#ffb594",
        secondary: "#005e6f",
        "on-secondary": "#ffffff",
        "secondary-container": "#c0f2fc",
        "on-secondary-container": "#002026",
        tertiary: "#689ab5",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#e2f1f8",
        "on-tertiary-container": "#081f2c",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#ffebd8",
        "primary-fixed-dim": "#ffb594",
        "on-primary-fixed": "#331200",
        "on-primary-fixed-variant": "#7b310e",
        "secondary-fixed": "#c0f2fc",
        "secondary-fixed-dim": "#93d5e0",
        "on-secondary-fixed": "#002026",
        "on-secondary-fixed-variant": "#004b59",
        "tertiary-fixed": "#e2f1f8",
        "tertiary-fixed-dim": "#b3cddc",
        "on-tertiary-fixed": "#081f2c",
        "on-tertiary-fixed-variant": "#344d5c",
        background: "#ffffff",
        "on-background": "#111827",
        "surface-variant": "#e5e7eb",
        "success-green": "#10B981",
        "warning-amber": "#F59E0B",
        "error-red": "#EF4444",
        "surface-gray": "#f9fafb",
        "border-subtle": "#e5e7eb",
      },
      fontFamily: {
        sans: ["Hanken Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      fontSize: {
        display: ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["2rem", { lineHeight: "2.5rem", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-lg-mobile": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "headline-md": ["1.5rem", { lineHeight: "2rem", fontWeight: "600" }],
        "body-lg": ["1.125rem", { lineHeight: "1.75rem", fontWeight: "400" }],
        "body-md": ["1rem", { lineHeight: "1.5rem", fontWeight: "400" }],
        "body-sm": ["0.875rem", { lineHeight: "1.25rem", fontWeight: "400" }],
        "label-md": ["0.875rem", { lineHeight: "1.25rem", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["0.75rem", { lineHeight: "1rem", letterSpacing: "0.02em", fontWeight: "500" }],
      },
      spacing: {
        xs: "8px",
        sm: "16px",
        md: "24px",
        lg: "40px",
        xl: "64px",
        gutter: "24px",
        "margin-mobile": "16px",
        "margin-desktop": "48px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        full: "9999px",
      },
      boxShadow: {
        ambient: "0 4px 24px 0 rgba(17, 24, 39, 0.08)",
        "ambient-teal": "0 4px 24px 0 rgba(0, 94, 111, 0.10)",
        dialog: "0 8px 32px 0 rgba(17, 24, 39, 0.12)",
      },
      maxWidth: {
        content: "1280px",
      },
      keyframes: {
        "slide-in-right": {
          "0%": { transform: "translateX(110%)", opacity: "0" },
          "100%": { transform: "translateX(0)", opacity: "1" },
        },
        "slide-out-right": {
          "0%": { transform: "translateX(0)", opacity: "1" },
          "100%": { transform: "translateX(110%)", opacity: "0" },
        },
      },
      animation: {
        "slide-in-right": "slide-in-right 0.25s ease-out forwards",
        "slide-out-right": "slide-out-right 0.2s ease-in forwards",
      },
    },
  },
  plugins: [],
};
export default config;
