import { Announcement, SystemEntry, User, AccessRequest } from './types'

export const mockAnnouncements: Announcement[] = [
  {
    id: 'ann-001',
    title: '2026 Q2 Performance Review Process',
    content: '<p>Dear Team,</p><p>The Q2 performance review cycle will begin on June 15th. All managers are required to complete reviews by June 30th. Please refer to the attached guidelines for the evaluation criteria.</p><p>Key dates:<br/>- Self-assessment due: June 17<br/>- Manager review: June 18-25<br/>- Calibration: June 26-28<br/>- Final submission: June 30</p>',
    department: 'People',
    audience: 'all',
    status: 'published',
    isPinned: true,
    isMandatoryRead: true,
    contactName: 'Sarah Chen',
    contactSlack: '@sarah-chen',
    publishedAt: '2026-06-01T09:00:00Z',
    expiresAt: '2026-07-01T00:00:00Z',
    createdAt: '2026-05-30T10:00:00Z',
    updatedAt: '2026-06-01T09:00:00Z',
    readCount: 142,
    totalAudience: 200,
  },
  {
    id: 'ann-002',
    title: 'New IT Security Policy: MFA Mandatory from July 1',
    content: '<p>Starting July 1, 2026, Multi-Factor Authentication (MFA) will be mandatory for all company systems. Please ensure you have set up MFA on your accounts before the deadline.</p>',
    department: 'IT',
    audience: 'all',
    status: 'published',
    isPinned: false,
    isMandatoryRead: true,
    contactName: 'IT Team',
    contactSlack: '@it-support',
    publishedAt: '2026-06-03T10:00:00Z',
    createdAt: '2026-06-02T14:00:00Z',
    updatedAt: '2026-06-03T10:00:00Z',
    readCount: 98,
    totalAudience: 200,
  },
  {
    id: 'ann-003',
    title: 'Q2 Sales Kickoff: Record Quarter Achievement',
    content: '<p>Congratulations to the GTM team for achieving 127% of our Q2 target! This is our best quarter ever. Details about the celebration event will follow.</p>',
    department: 'GTM',
    audience: 'dept',
    audienceTarget: 'GTM & Sales',
    status: 'published',
    isPinned: false,
    isMandatoryRead: false,
    contactName: 'Marcus Lee',
    publishedAt: '2026-06-05T08:00:00Z',
    createdAt: '2026-06-04T16:00:00Z',
    updatedAt: '2026-06-05T08:00:00Z',
  },
  {
    id: 'ann-004',
    title: 'Benefits Open Enrollment Reminder',
    content: '<p>Benefits open enrollment ends June 30. Please review your options and make any changes in the benefits portal.</p>',
    department: 'People',
    audience: 'all',
    status: 'draft',
    isPinned: false,
    isMandatoryRead: false,
    createdAt: '2026-06-07T11:00:00Z',
    updatedAt: '2026-06-07T11:00:00Z',
  },
  {
    id: 'ann-005',
    title: 'Engineering All-Hands: Platform Reliability Update',
    content: '<p>Join us this Friday for an engineering all-hands focused on our platform reliability improvements in Q2 and our roadmap for Q3.</p>',
    department: 'Engineering',
    audience: 'dept',
    audienceTarget: 'IT & Engineering',
    status: 'pending',
    isPinned: false,
    isMandatoryRead: false,
    contactName: 'Alex Kim',
    createdAt: '2026-06-08T09:00:00Z',
    updatedAt: '2026-06-08T09:00:00Z',
  },
]

export const mockSystems: SystemEntry[] = [
  {
    id: 'sys-001',
    name: 'Slack',
    description: 'Team communication and collaboration platform',
    url: 'https://slack.com',
    iconUrl: 'https://cdn.brandfetch.io/idp7u7dAEj/theme/dark/icon.png?c=1dxbfHSJFAPEWhkg5rG',
    category: 'IT & Engineering',
    status: 'active',
    ownerName: 'IT Team',
    ownerEmail: 'it@company.com',
    ownerSlack: '@it-support',
    isQuickAccess: true,
    myAccessStatus: 'connected',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-002',
    name: 'Notion',
    description: 'All-in-one workspace for notes, docs, and project management',
    url: 'https://notion.so',
    iconUrl: 'https://cdn.brandfetch.io/idVfgzXAnT/theme/dark/icon.png?c=1dxbfHSJFAPEWhkg5rG',
    category: 'IT & Engineering',
    status: 'active',
    ownerName: 'IT Team',
    ownerEmail: 'it@company.com',
    ownerSlack: '@it-support',
    isQuickAccess: true,
    myAccessStatus: 'connected',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-003',
    name: 'HubSpot',
    description: 'CRM platform for sales, marketing, and customer success',
    url: 'https://hubspot.com',
    category: 'GTM & Sales',
    status: 'active',
    ownerName: 'Marcus Lee',
    ownerEmail: 'marcus@company.com',
    ownerSlack: '@marcus-gtm',
    isQuickAccess: true,
    myAccessStatus: 'none',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-004',
    name: 'Workday',
    description: 'HR management system for payroll, benefits, and performance',
    url: 'https://workday.com',
    category: 'HR & Benefits',
    status: 'active',
    ownerName: 'Sarah Chen',
    ownerEmail: 'sarah@company.com',
    ownerSlack: '@sarah-hr',
    isQuickAccess: true,
    myAccessStatus: 'connected',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-005',
    name: 'NetSuite',
    description: 'Enterprise ERP and financial management system',
    url: 'https://netsuite.com',
    category: 'Finance',
    status: 'active',
    ownerName: 'Finance Team',
    ownerEmail: 'finance@company.com',
    ownerSlack: '@finance-ops',
    isQuickAccess: false,
    myAccessStatus: 'pending',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-006',
    name: 'GitHub',
    description: 'Source code management and collaboration platform',
    url: 'https://github.com',
    category: 'IT & Engineering',
    status: 'active',
    ownerName: 'Engineering Platform',
    ownerEmail: 'platform@company.com',
    ownerSlack: '@platform-team',
    isQuickAccess: true,
    myAccessStatus: 'connected',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-007',
    name: 'Jira',
    description: 'Project tracking and issue management for engineering and product',
    url: 'https://atlassian.com/jira',
    category: 'IT & Engineering',
    status: 'active',
    ownerName: 'Engineering Platform',
    ownerEmail: 'platform@company.com',
    ownerSlack: '@platform-team',
    isQuickAccess: false,
    myAccessStatus: 'connected',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-008',
    name: '1Password',
    description: 'Password manager and security tool for all employees',
    url: 'https://1password.com',
    category: 'IT & Engineering',
    status: 'active',
    ownerName: 'IT Security',
    ownerEmail: 'security@company.com',
    ownerSlack: '@it-security',
    isQuickAccess: false,
    myAccessStatus: 'connected',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-009',
    name: 'Gong',
    description: 'Revenue intelligence platform for sales call recording and analysis',
    url: 'https://gong.io',
    category: 'GTM & Sales',
    status: 'active',
    ownerName: 'Sales Ops',
    ownerEmail: 'sales-ops@company.com',
    isQuickAccess: false,
    myAccessStatus: 'none',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
  {
    id: 'sys-010',
    name: 'Greenhouse',
    description: 'Recruiting and applicant tracking system',
    url: 'https://greenhouse.io',
    category: 'HR & Benefits',
    status: 'active',
    ownerName: 'Recruiting Team',
    ownerEmail: 'recruiting@company.com',
    ownerSlack: '@recruiting',
    isQuickAccess: false,
    myAccessStatus: 'none',
    createdAt: '2026-01-01T00:00:00Z',
    updatedAt: '2026-06-01T00:00:00Z',
  },
]

export const mockUsers: User[] = [
  {
    id: 'user-001',
    email: 'sarah.chen@company.com',
    name: 'Sarah Chen',
    role: 'dept_admin',
    department: 'People',
    createdAt: '2025-01-15T00:00:00Z',
  },
  {
    id: 'user-002',
    email: 'marcus.lee@company.com',
    name: 'Marcus Lee',
    role: 'dept_admin',
    department: 'GTM & Sales',
    createdAt: '2025-02-01T00:00:00Z',
  },
  {
    id: 'user-003',
    email: 'alex.kim@company.com',
    name: 'Alex Kim',
    role: 'employee',
    department: 'Engineering',
    createdAt: '2025-03-10T00:00:00Z',
  },
  {
    id: 'user-004',
    email: 'priya.patel@company.com',
    name: 'Priya Patel',
    role: 'employee',
    department: 'Finance',
    createdAt: '2025-04-05T00:00:00Z',
  },
  {
    id: 'user-005',
    email: 'david.wang@company.com',
    name: 'David Wang',
    role: 'platform_admin',
    department: 'IT',
    createdAt: '2025-01-01T00:00:00Z',
  },
  {
    id: 'user-006',
    email: 'emma.johnson@company.com',
    name: 'Emma Johnson',
    role: 'employee',
    department: 'HR & Benefits',
    createdAt: '2025-05-20T00:00:00Z',
  },
  {
    id: 'user-007',
    email: 'ryan.chen@company.com',
    name: 'Ryan Chen',
    role: 'employee',
    department: 'Engineering',
    createdAt: '2025-06-01T00:00:00Z',
  },
  {
    id: 'user-008',
    email: 'lisa.zhang@company.com',
    name: 'Lisa Zhang',
    role: 'dept_admin',
    department: 'Finance',
    createdAt: '2025-02-15T00:00:00Z',
  },
]

export const mockAccessRequests: AccessRequest[] = [
  {
    id: 'req-001',
    systemId: 'sys-003',
    systemName: 'HubSpot',
    requesterName: 'Alex Kim',
    requesterEmail: 'alex.kim@company.com',
    status: 'pending',
    note: 'Need access for Q3 campaign tracking',
    createdAt: '2026-06-07T14:00:00Z',
  },
  {
    id: 'req-002',
    systemId: 'sys-009',
    systemName: 'Gong',
    requesterName: 'Emma Johnson',
    requesterEmail: 'emma.johnson@company.com',
    status: 'pending',
    note: 'Joining sales enablement team',
    createdAt: '2026-06-06T10:00:00Z',
  },
  {
    id: 'req-003',
    systemId: 'sys-005',
    systemName: 'NetSuite',
    requesterName: 'Ryan Chen',
    requesterEmail: 'ryan.chen@company.com',
    status: 'approved',
    note: 'Finance internship project',
    reviewNote: 'Approved for read-only access',
    createdAt: '2026-06-04T09:00:00Z',
    reviewedAt: '2026-06-05T11:00:00Z',
  },
]
